### ISSUE TITLE
Is this module available on npmjs

### ISSUE THREAD

**Issue by peternhale** [sularome/JavaScript-Algorithms#1]
I was wondering if this module is available on npmjs? Could not find a reference using name assigned in package.json.

**Comment by sularome** [comment]
Hi Peter,
I haven't put it on npm yet, but it's a good idea. I will let you know once i publish it.

**Comment by sularome** [comment]
Hi,

I have published the package [here](https://www.npmjs.com/package/typescript-algorithms-and-datastructures)
I will be happy to know your feedback.
Keep in mind that this is very early version and shouldn't be used on production.

**Comment by peternhale** [comment]
Thank you @sularome. I have presented this module to a number of my peers that are heavily involved in typescript development and it has raised great interest. Thank you for the hard work!
